### ISSUE TITLE
reference to a possible application

### ISSUE THREAD

**Issue by jwaldmann** [bkomuves/compact-word-vectors#1]
not a bug, just adding a reference: your library was mentioned at https://mail.haskell.org/pipermail/haskell-cafe/2021-May/133992.html and I might use it to improve https://gitlab.imn.htwk-leipzig.de/waldmann/tf (unify TF[34].hs)

**Comment by bkomuves** [comment]
Ok, I'll close this then.

Please report if you run into any issues - while there is a testsuite, the library haven't seen much usage yet.

Also unfortunately from the very limited experience it doesn't look necessarily faster than just using `[Int]`... So it may only make sense when memory is a limited resource.

**Comment by jwaldmann** [comment]
OK.

"not necessarily faster than [Int]" - then it should be used as a GHC test case ... (test that the simplifier really unfolds/inlines everything). 

Perhaps there'll be more insights on the mailing list thread.
